/* Generated by gep (123/06/18 13:34:17) copyright (c) 2008 IRIT - UPS */

#include <assert.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <toy/api.h>
#include "platform.h"
#include <toy/env.h>
#include <toy/macros.h>
#include <toy/config.h>


static char *toy_string_ident[] = {
	"TOY_UNKNOWN",
	"TOY_BEQ_S__S__D",
	"TOY_ADD_S__S__S",
	"TOY_SET_S___ID"
};

/* execution code table */
typedef void (*toy_code_function_t)(toy_state_t *, toy_inst_t *);
extern toy_code_function_t toy_code_table[];


char *toy_get_string_ident(toy_ident_t id)
{
	return toy_string_ident[id];
}

static unsigned long toy_size_ident[] = {
	16,
	16,
	16,
	16
};

unsigned long toy_get_inst_size_from_id(toy_ident_t id) {
	return toy_size_ident[id];
}

unsigned long toy_get_inst_size(toy_inst_t* inst) {
	return toy_size_ident[inst->ident];
}

/**
 * @typedef toy_platform_t
 * This opaque type allows to represent an hardware and software platform.
 * It includes information about:
 * @li the hardware memories,
 * @li the module data (including system calls and interruption support).
 */


/**
 * Build a new platform for the platform toy.
 * @return	Created platform or null if there is no more memory (see errno).
 * @note To release the platform, use toy_unlock_platform().
 */
toy_platform_t *toy_new_platform(void) {
	toy_platform_t *pf;

	/* allocation */
	pf = (toy_platform_t *)calloc(1, sizeof(toy_platform_t));
	if(pf == NULL) {
		errno = ENOMEM;
		return NULL;
	}
	/* the new platform is not locked yet */
	pf->usage = 0;

	/* other init */
	/*pf->entry = pf->sp = pf->argv = pf->envp = pf->aux = pf->argc = 0;*/
	pf->sys_env = calloc(1, sizeof(toy_env_t));
	if(pf->sys_env == NULL) {
		errno = ENOMEM;
		free(pf);
		return NULL;
	}

	/* memory initialization */
	pf->mems.named.M = toy_mem_new();
	if(pf->mems.named.M == NULL) {
		free(pf->sys_env);
		free(pf);
		return NULL;
	}


	/* module initialization */
	TOY_MEM_INIT(pf);
	TOY_GRT_INIT(pf);
	TOY_ERROR_INIT(pf);
	TOY_GEN_INT_INIT(pf);
	TOY_LOADER_INIT(pf);
	TOY_CODE_INIT(pf);


	/* return platform */
	return pf;
}


/**
 * Get a memory in the platform.
 * @param platform	Platform to get memory from.
 * @param index		Index of the memory to get.
 * @return			Requested memory.
 */
toy_memory_t *toy_get_memory(toy_platform_t *platform, int index) {
	if (platform == NULL)
		return NULL;

	return platform->mems.array[index];
}


/**
 * return the system info (argc, argv ...), meaningless
 * if used when no program loaded
 * @param	platform	Platform to get system info from.
 * @return		Requested system info.
 */
toy_env_t *toy_get_sys_env(toy_platform_t *platform)
{
	if (platform == NULL)
		return NULL;

	return platform->sys_env;
}


/**
 * Ensure that the platform is not released before a matching
 * toy_platform_unlock() is performed.
 * @param platform	Platform to lock.
 */
void toy_lock_platform(toy_platform_t *platform) {
	if (platform == NULL)
		return;

	platform->usage++;
}


/**
 * Unlock the platform. If it the last lock on the platform,
 * the platform is freed.
 * @param platform	Platform to unlock.
 */
void toy_unlock_platform(toy_platform_t *platform) {
	if (platform == NULL)
		return;

	/* unlock */
	if(--platform->usage != 0)
		return;

	/* destroy the modules */
	TOY_MEM_DESTROY(platform);
	TOY_GRT_DESTROY(platform);
	TOY_ERROR_DESTROY(platform);
	TOY_GEN_INT_DESTROY(platform);
	TOY_LOADER_DESTROY(platform);
	TOY_CODE_DESTROY(platform);


	/* free the memories */
	toy_mem_delete(platform->mems.named.M);


	/* free system info */
	free(platform->sys_env);

	/* free the platform */
	free(platform);
	platform = NULL;
}


/**
 * Load the program from the given loader.
 * @param platform		Platform.
 * @param loader		Loader to get program from.
 */
void toy_load(toy_platform_t *platform, toy_loader_t *loader) {
	assert(platform);

	/* load in platform's memory */
	toy_loader_load(loader, platform);

	/* initialize system information */
	platform->entry = toy_loader_start(loader);
	toy_set_brk(platform, toy_brk_init(loader));

	/* !!TODO!! add argc,argv... init */
	/* stack initialization */
	toy_stack_fill_env(loader, platform, platform->sys_env);
}


/**
 * Load the given program in the platform and initialize stack
 * @param platform	Platform to load in.
 * @param path		Path of the file to load.
 * @return			0 for success, -1 for error (in errno).
 */
int toy_load_platform(toy_platform_t *platform, const char *path) {
	toy_loader_t *loader;
	assert(platform);

	/* open the file */
	loader = toy_loader_open(path);
	if(loader == NULL)
		return -1;

	/* load in platform's memory */
	toy_load(platform, loader);

	/* close the file */
	toy_loader_close(loader);

	/* return success */
	return 0;
}



/* state management function */


/**
 * Create a new initialized state depending on a given platform
 * @param	platform	the platform helping the simulation on the created state
 * @return			a new initialized state suitable for the given platform
 */
toy_state_t *toy_new_state(toy_platform_t *platform)
{
	toy_state_t *state;

	/* allocation */
	state = (toy_state_t *)malloc(sizeof(toy_state_t));
	if(state == NULL)
	{
		errno = ENOMEM;
		return NULL;
	}

	/* zeroing of all registers and memory references */
	memset(state, 0, sizeof(toy_state_t));

	/* creating platform */
	if(platform == NULL)
	{
		free(state);
		return NULL;
	}
	state->platform = platform;

	/* locking it */
	toy_lock_platform(state->platform);

	/* memory initialization */
	state->M = state->platform->mems.named.M;

	/* proper state initialization (from the op init) */


	/* PC initialization */
	state->PC = platform->entry;
#	ifdef TOY_INIT_PC
		TOY_INIT_PC
#	else
		state->PC = platform->entry;
#	endif


	/* system registers initialization (argv, envp...) */
	toy_registers_fill_env(platform->sys_env, state);

	return state;
}


/**
 * Delete a state
 * @param	state	the state to delete
 */
void toy_delete_state(toy_state_t *state)
{
	if (state == NULL)
		return;

	/* unlock the platform */
	toy_unlock_platform(state->platform);

	/* free the state */
	free(state);
	state = NULL;
}


/**
 * Return a copy of a given state, both state will share the same memory
 * and each new state's register will have the same value as in the given state.
 * the copied state may not be suitable for further simulation as the stack pointers
 * and similar address registers will be identical in two different states
 * sharing the same memory
 *
 * @param	state	the state to copy
 * @return		a fresh allocated copy (to be freed by the caller)
 */
toy_state_t *toy_copy_state(toy_state_t *state)
{
	int i;

	if (state == NULL)
		return NULL;

	/* allocate a new state */
	toy_state_t *new_state = (toy_state_t *)malloc(sizeof(toy_state_t));
	if(new_state == NULL)
	{
		errno = ENOMEM;
		return NULL;
	}

	/* copy the platform and lock it */
	/* !!WARNING!! is this needed? as we may not wish to simulate with this state */
	new_state->platform = state->platform;
	toy_lock_platform(new_state->platform);

	/* copy all the registers */
	for (i = 0; i < 16; i++)
		new_state->R[i] = state->R[i];
	new_state->PC = state->PC;

	/* copy the references to the memory */
	new_state->M = state->M;


	return new_state;
}


/**
 * Return a copy of a given state which will be intended for a further simulation,
 * both state will share the same memory
 * and each new state's register will have the same value as in the given state.
 *
 * TODO: we want to be able to simulate on this forked state
 * so we should really care about stack pointer and other address registers
 * used to write data in memory, these should have a different value
 * for each state created as we share the same memory
 *
 * @param	state	the state to fork
 * @return		a fresh allocated copy (to be freed by the caller)
 */
toy_state_t *toy_fork_state(toy_state_t *state)
{
	int i;

	if (state == NULL)
		return NULL;

	/* allocate a new state */
	toy_state_t *new_state = (toy_state_t *)malloc(sizeof(toy_state_t));
	if(new_state == NULL)
	{
		errno = ENOMEM;
		return NULL;
	}

	/* copy the platform and lock it */
	new_state->platform = state->platform;
	toy_lock_platform(new_state->platform);

	/* copy all the registers */
	for (i = 0; i < 16; i++)
		new_state->R[i] = state->R[i];
	new_state->PC = state->PC;

	/* copy the references to the memory */
	new_state->M = state->M;

}


/**
 * Dump all register values of a given state to the given output
 *
 * @param	state	the state whose registers we wish to dump
 * @param	out	the file to dump within, typically stderr or stdout
 */
void toy_dump_state(toy_state_t *state, FILE *out)
{
	int i;

	/* dump all the registers */
	fprintf(out, "R\n");
	for (i = 0; i < 16; i++) {
		fprintf(out, "\t[%d] = %04X", i, state->R[i]);
		if(i % 4 == 3)
			fputc('\n', out);
	}
	if(i % 4 != 3)
		fputc('\n', out);
	fprintf(out, "PC = %04X\n", state->PC);

}


/**
 * Output the header of a CSV validation output.
 * @param out	File to output to.
 */
void toy_output_header_valid(FILE *out) {
	fputs("# PC", out);

	fputc('\n', out);
}


/**
 * Output the given state for validation. The first column is the address
 * of the current instruction and next ones are the register.
 * @param state		State to dump.
 * @param out		File to output to.
 */
void toy_output_state_valid(toy_state_t *state, FILE *out) {

#	define GLISS_GET_I(v)	fprintf(out, "\t%08x", (v))
#	define GLISS_GET_L(v)	fprintf(out, "\t%016llx", (v))

	fprintf(out, "%08x", state->PC);

	fputc('\n', out);
}


/**
 * return a reference (a pointer in fact) towards the platform of a given state
 *
 * @param	state	the state we want to access the platform
 * @return		the address of the platform of the given state
 */
toy_platform_t *toy_platform(toy_state_t *state)
{
	if (state == NULL)
		return NULL;

	/* return the platform */
	return state->platform;
}


/* simulation functions */


/**
 * Create a new simulator structure with the given state
 * @param	state	the state on which we intend to simulate
 * @param	start_addr	the beginning of the execution (useful for executables compiled with no _start symbol),
 *				if null we leave the PC in its previous state given by the loader
 * @param	exit_addr	the explicitly given last instruction address to simulate, if null we will stop running in another way
 */
toy_sim_t *toy_new_sim(toy_state_t *state, toy_address_t start_addr, toy_address_t exit_addr)
{
	toy_sim_t *sim;

	if (state == NULL)
		return NULL;

	/* allocate a new simulator */
	sim = (toy_sim_t *)malloc(sizeof(toy_sim_t));
	if(sim == NULL)
	{
		errno = ENOMEM;
		return NULL;
	}

	/* link the state to the new simulator */
	sim->state = state;

	/* create a new decoder */
	sim->decoder = toy_new_decoder(toy_platform(state));
	if (sim->decoder == NULL)
		return NULL;
	sim->addr_exit = exit_addr;
	if (start_addr)
		sim->state->PC = start_addr;

	/* not ended at start */
	sim->ended = 0;
	return sim;
}


//======================================================================
#if !defined(TOY_TRACE_CACHE) && !defined(TOY_DTRACE_CACHE)

/**
 * Return the next instruction to be executed by the given simulator
 *
 * this instruction is pointed by the PC
 *
 * @param	sim	the simulator which we simulate within
 * @return		the next instruction to be executed, fully decoded
 */
toy_inst_t *toy_next_inst(toy_sim_t *sim)
{
	/* retrieving the instruction (which is allocated by the decoder) */
	/* we let the caller check for error */
	return toy_decode(sim->decoder, sim->state->PC);
}


/**
 * Execute the next instruction in the given simulator.
 * It doesn't check if we reached the last instruction, so it should be done
 * separately using the function toy_is_sim_ended
 * @param	sim	the simulator which we simulate within
 */
void toy_step(toy_sim_t *sim)
{
	toy_inst_t*  inst;
	toy_state_t* state = sim->state;

	/* retrieving next instruction */
    inst = toy_decode(sim->decoder, state->PC);

	/* execute it */

	toy_code_table[inst->ident](state, inst);

#ifndef TOY_INF_DECODE_CACHE
#ifndef TOY_FIXED_DECODE_CACHE
#ifndef TOY_LRU_DECODE_CACHE
    /* finally free it */
	toy_free_inst(inst);
#endif
#endif
#endif

	/* ended ? */
	if(sim->addr_exit == state->PC)
		sim->ended = 1;
}

/**
 * Straightforward execution of the simulated programm.
 * It runs and count the number of executed instructions
 * until the programm reached the last instruction.
 * this is the <bold> fastest </bold> way to simulate a programm
 * @param	sim	the simulator which we simulate within
 * @return number of executed instructions
 * */
uint64_t toy_run_and_count_inst(toy_sim_t *sim)
{
	uint64_t i = 0;
    toy_state_t*   state     = sim->state;
    toy_decoder_t* decoder   = sim->decoder;
    toy_address_t  addr_exit = sim->addr_exit;
	toy_inst_t* inst;
	while(!sim->ended) {
		inst = toy_decode(decoder, state->PC);
		toy_code_table[inst->ident](state, inst);
#ifndef TOY_INF_DECODE_CACHE
#ifndef TOY_FIXED_DECODE_CACHE
#ifndef TOY_LRU_DECODE_CACHE
    /* finally free it */
	toy_free_inst(inst);
#endif
#endif
#endif
		i++;
		if(addr_exit == state->PC)
			sim->ended = 1;
	}
	return i;
}

/**
 * Straightforward execution of the simulated programm.
 * It runs until the programm reached the last instruction.
 * this is the <bold> fastest </bold> way to simulate a programm
 * @param	sim	the simulator which we simulate within
 * */
void toy_run_sim(toy_sim_t *sim)
{
	toy_state_t*   state     = sim->state;
    toy_decoder_t* decoder   = sim->decoder;
    toy_address_t  addr_exit = sim->addr_exit;
	toy_inst_t* inst;
	while(!sim->ended) {
		inst = toy_decode(decoder, state->PC);
		toy_code_table[inst->ident](state, inst);
#ifndef TOY_INF_DECODE_CACHE
#ifndef TOY_FIXED_DECODE_CACHE
#ifndef TOY_LRU_DECODE_CACHE
    /* finally free it */
		toy_free_inst(inst);
#endif
#endif
#endif
		if(addr_exit == state->PC)
			sim->ended = 1;
	}
}
#endif
//======================================================================
#ifdef TOY_TRACE_CACHE
/**
 * Return the next instruction to be executed by the given simulator
 *
 * this instruction is pointed by the PC
 *
 * @param	sim	the simulator which we simulate within
 * @return		the next instruction to be executed, fully decoded
 */
toy_inst_t *toy_next_inst(toy_sim_t *sim)
{
	/* retrieving the instruction (which is allocated by the decoder) */
	/* we let the caller check for error */
	return toy_decode(sim->decoder, sim->state->PC) + ((sim->state->NIA >> 2) & (TRACE_DEPTH-1));
}


/**
 * Execute the next instruction in the given simulator.
 * It doesn't check if we reached the last instruction, so it should be done
 * separately using the function toy_is_sim_ended
 * @param	sim	the simulator which we simulate within
 */
void toy_step(toy_sim_t *sim)
{
	toy_inst_t*  inst;
	toy_state_t* state = sim->state;

	/* retrieving next instruction */
    inst =  toy_decode(sim->decoder, state->PC) + ((sim->state->NIA >> 2) & (TRACE_DEPTH-1));

	/* execute it */

	toy_code_table[inst->ident](state, inst);

	/* ended ? */
	if(sim->addr_exit == state->PC)
		sim->ended = 1;
}


/**
 * Straightforward execution of the simulated programm.
 * It runs and count the number of executed instructions
 * until the programm reached the last instruction.
 * this is the <bold> fastest </bold> way to simulate a programm
 * @param	sim	the simulator which we simulate within
 * @return number of executed instructions
 * */
uint64_t toy_run_and_count_inst(toy_sim_t *sim)
{
	uint64_t i = 0;
    uint32_t num_bloc;
    toy_state_t*   state     = sim->state;
    toy_decoder_t* decoder   = sim->decoder;
    toy_address_t  addr_exit = sim->addr_exit;
    toy_inst_t*    inst, *trace;

	while(!sim->ended)
	{
        trace    = toy_decode(decoder, state->PC);
        num_bloc = (state->PC >> 2) >> TRACE_DEPTH_PW;

        while((((state->PC >> 2)>> TRACE_DEPTH_PW) == num_bloc) && (!sim->ended) && (addr_exit != state->PC))
        {
			inst = trace + ((state->NIA >> 2) & (TRACE_DEPTH-1));
			}
			i++;
		}

		/* ended ? */
		if(addr_exit == state->PC)
			sim->ended = 1;
	}
	return i;
}

/**
 * Straightforward execution of the simulated programm.
 * It runs until the programm reached the last instruction.
 * this is the <bold> fastest </bold> way to simulate a programm
 * @param	sim	the simulator which we simulate within
 * */
void toy_run_sim(toy_sim_t *sim)
{
    uint32_t num_bloc;
    toy_state_t*   state     = sim->state;
    toy_decoder_t* decoder   = sim->decoder;
    toy_address_t  addr_exit = sim->addr_exit;
    toy_inst_t*    inst, *trace;

	while(addr_exit != state->PC)
	{
        trace    = toy_decode(decoder, state->PC);
        num_bloc = (state->PC >> 2) >> TRACE_DEPTH_PW;

        while((((state->PC >> 2)>> TRACE_DEPTH_PW) == num_bloc) && (addr_exit != state->PC))
        {
			inst = trace + ((state->NIA >> 2) & (TRACE_DEPTH-1));
		    toy_code_table[inst->ident](state, inst);
        }
	}
}
#endif
//======================================================================
#ifdef TOY_DTRACE_CACHE
/**
 * Return the next instruction to be executed by the given simulator
 *
 * this instruction is pointed by the PC
 *
 * @param	sim	the simulator which we simulate within
 * @return		the next instruction to be executed, fully decoded
 */
toy_inst_t *toy_next_inst(toy_sim_t *sim)
{
	/* retrieving the instruction (which is allocated by the decoder) */
	/* we let the caller check for error */

	/* Static variable is an optimisation hack
	 * in order to cache the current trace */
	static toy_inst_t*  inst = 0;
	toy_state_t* state = sim->state;

	/* retrieving next instruction */
	if(inst != 0)
	{
		inst++;
		if(inst->ident == -1)
			inst =  toy_decode(sim->decoder, state->PC);
	}else
	{
		inst =  toy_decode(sim->decoder, state->PC);
	}
	return inst;
}


/**
 * Execute the next instruction in the given simulator.
 * It doesn't check if we reached the last instruction, so it should be done
 * separately using the function toy_is_sim_ended
 * @param	sim	the simulator which we simulate within
 */
void toy_step(toy_sim_t *sim)
{
	/* Static variable is an optimisation hack
	 * in order to cache the current trace */
	static toy_inst_t*  inst = 0;
	toy_state_t* state = sim->state;

	/* retrieving next instruction */
	if(inst != 0)
	{
		inst++;
		if(inst->ident == -1)
			inst =  toy_decode(sim->decoder, state->PC);
	}else
	{
		inst =  toy_decode(sim->decoder, state->PC);
	}


	/* execute it */

	toy_code_table[inst->ident](state, inst);

		if(sim->addr_exit == state->PC)
			sim->ended = 1;
}


/**
 * Straightforward execution of the simulated programm.
 * It runs and count the number of executed instructions
 * until the programm reached the last instruction.
 * this is the <bold> fastest </bold> way to simulate a programm
 * @param	sim	the simulator which we simulate within
 * @return number of executed instructions
 * */
uint64_t toy_run_and_count_inst(toy_sim_t *sim)
{
	uint64_t i = 0;
    toy_state_t*   state     = sim->state;
    toy_decoder_t* decoder   = sim->decoder;
    toy_address_t  addr_exit = sim->addr_exit;
    toy_inst_t*    inst;

	while(!sim->ended)
	{
        inst = toy_decode(decoder, state->PC);

        while( (inst->ident != -1) && (!sim->ended) && (addr_exit != state->PC))
        {
		    toy_code_table[inst->ident](state, inst);
			inst++;
			i++;
        }

        /* ended ? */
		if(addr_exit == state->PC)
			sim->ended = 1;

	}
	return i;
}

/**
 * Straightforward execution of the simulated programm.
 * It runs until the programm reached the last instruction.
 * this is the <bold> fastest </bold> way to simulate a programm
 * @param	sim	the simulator which we simulate within
 * */
void toy_run_sim(toy_sim_t *sim)
{
    uint32_t num_bloc;
    toy_state_t*   state     = sim->state;
    toy_decoder_t* decoder   = sim->decoder;
    toy_address_t  addr_exit = sim->addr_exit;
    toy_inst_t*    inst;

	while(!sim->ended)
	{
        inst = toy_decode(decoder, state->PC);

        while( (inst->ident != -1) && (addr_exit != state->PC))
        {
		    toy_code_table[inst->ident](state, inst);
			inst++;
        }

        /* ended ? */
		if(addr_exit == state->PC)
			sim->ended = 1;
	}
}

#endif
//======================================================================
/**
 * @fn int toy_is_sim_ended(toy_sim_t *sim);
 * Indicate if the simulation is finished on the given simulator
 * @param	sim	the simulator which we simulate within
 * @return	whether or not the simulation is ended (0 => false, anything!=0 => true)
 */

/**
 * destruction of a simulator object, the associated state and decoder are also destroyed
 * @param	sim	the simulator to be deleted
 */
void toy_delete_sim(toy_sim_t *sim)
{
	if (sim == NULL)
		return;

	/* delete the decoder */
	toy_delete_decoder(sim->decoder);

	/* delete the state */
	toy_delete_state(sim->state);

	/* delete the sim */
	free(sim);
}


/**
 * Get the address of the next instruction to be executed,
 * indicated by PC
 * @param sim	Simulator to work with.
 * @return		Address of the current instruction.
 */
toy_address_t  toy_next_addr(toy_sim_t *sim) {
	assert(sim);
	return sim->state->PC;
}


/**
 * Set the address of the next instruction.
 * @param sim		Current simulator.
 * @param address	Next address.
 */
void toy_set_next_address(toy_sim_t *sim, toy_address_t address) {
	assert(sim);
	sim->state->PC = address;
}


/**
 * Set the exit address for simulation.
 * @param sim		Current simulator.
 * @param address	Exit address.
 */
void toy_set_exit_address(toy_sim_t *sim, toy_address_t address) {
	sim->addr_exit = address;
}


/**
 * Null-name ended list, provides the list of available decoding modes.
 */
toy_mode_t toy_modes[] = {
	{ "toy", toy_decode },
	{ 0, 0 }
};
