/* Generated by gep ($(date)) copyright (c) 2008 IRIT - UPS */

#include <stdlib.h>
#include <stdio.h>
#include <toy/fetch.h>
#include <toy/decode.h> /* api.h will be in it, for fetch functions, decode_table.h also */
#include <toy/config.h> /* for memory endiannesses */
#include <toy/code.h>

#include "code_table.h"


/**
 * Execute the given instruction in the given state.
 * @param state		Current execution state.
 * @param inst		Current instruction to execute.
 */
void toy_execute(toy_state_t *state, toy_inst_t *inst)
{
	toy_code_table[inst->ident](state, inst);
}


/* End of file toy_code.c */
