/* Generated by gep (123/06/18 13:34:17) copyright (c) 2011 IRIT - UPS */

#include <assert.h>
#include <toy/debug.h>
#include <toy/macros.h>
#include <toy/grt.h>

#define GLISS_IDX		idx
#define GLISS_I			r.iv
#define GLISS_L			r.lv
#define GLISS_F			r.fv
#define GLISS_D			r.dv
#define GLISS_GET_I(a)	r.iv = a
#define GLISS_GET_L(a)	r.lv = a
#define GLISS_GET_F(a)	r.fv = a
#define GLISS_GET_D(a)	r.dv = a

static register_bank_t toy_registers[] = {
	{
		1,
		"R",
		"R%d",
		16,
RTYPE_INT,
		16
	},
	{
		2,
		"PC",
		"PC",
		1,
RTYPE_ADDR,
		16
	},
	{
		-1
	}
};


/**
 * Get the description of registers of the architecture.
 * @return		Array of registers (last one has a negative identifier).
 */
register_bank_t *toy_get_registers(void) {
	return toy_registers;
}

/**
 * Get the value of a register.
 * @param state		Current state.
 * @param id		Register identifier (from register_bank_t).
 * @param idx		Index in the bank (ignored for non-mutiple register bank).
 * @return			Value of the register.
 */
register_value_t toy_get_register(toy_state_t *state, int id, int idx) {
	register_value_t r;
	switch(id) {
	case 1: {
				GLISS_GET_I(TOY_R[GLISS_IDX]);

		} break;
	case 2: {
				GLISS_GET_I(TOY_PC);

		} break;

	default:
		assert(0);
	}
	return r;
}


/**
 * Set the value of a register in the given state.
 * @param state		Current state.
 * @param id		Register identifier (from register_bank_t).
 * @param idx		Index in the bank (ignored for non-mutiple register bank).
 * @param value		Value to put in register.
 */
void toy_set_register(toy_state_t *state, int id, int idx, register_value_t r) {
	switch(id) {
	case 1: {
				TOY_R[GLISS_IDX] = GLISS_I;

		} break;
	case 2: {
				TOY_PC = GLISS_I;

		} break;

	default:
		assert(0);
	}
}


/* handle of exceptions */


/* list of exceptions */
static toy_exception_t exceptions[] = {
	{ 0, 0, 0 }
};


/**
 * Get the list of exceptions.
 * @return	List of exceptions ended by an item whose name is null.
 */
toy_exception_t *toy_exceptions(void) {
	return exceptions;
}

