/* Generated by GLISS V2.0 Copyright (c) 2009 IRIT - UPS (123/06/18 13:34:17) */
#ifndef TOY_PLATFORM_H
#define TOY_PLATFORM_H

#include <toy/api.h>
#include <toy/mem.h>
#include <toy/grt.h>
#include <toy/error.h>
#include <toy/gen_int.h>
#include <toy/loader.h>
#include <toy/code.h>


/* toy_platform_t structure */
struct toy_platform_t
{
	int usage;

	/* entry point of the simulated program */
	toy_address_t entry;
	/* initial sp, argv, envp ... */
	toy_env_t *sys_env;

	union
	{
		toy_memory_t *array[0];
		struct
		{
			toy_memory_t *M;

		} named;
	} mems;
	TOY_MEM_STATE
	TOY_GRT_STATE
	TOY_ERROR_STATE
	TOY_GEN_INT_STATE
	TOY_LOADER_STATE
	TOY_CODE_STATE

};

/* functions */

#endif	/* TOY_PLATFORM_H */
