#!/bin/bash

function syntax {
	echo "SYNTAX: gliss-config [--cflags] [--libs]"
	echo "	--cflags -- output C flags"
	echo "	--libs -- output linked libraries"
}

while test "$1" != ""; do
	case "$1" in
		--cflags)
			echo "-I'/home/oussama/backup/gliss2/toy/include'"
			;;
        --libs)
        	echo "-L'/home/oussama/backup/gliss2/toy/src' -ltoy      "
			;;
        --help|-h)
        		syntax
        		exit 0
                ;;
        *)
        		echo "ERROR: unknown option $1"
        		syntax
                exit 1
                ;;
        esac
        shift
done
