/* Generated by gep ($(date)) copyright (c) 2008 IRIT - UPS */

#ifndef TOY_TOY_INCLUDE_TOY_CODE_H
#define TOY_TOY_INCLUDE_TOY_CODE_H


#if defined(__cplusplus)
extern  "C"
{
#endif


#define TOY_CODE_STATE
#define TOY_CODE_INIT(s)
#define TOY_CODE_DESTROY(s)

#if defined(__cplusplus)
}
#endif

#endif /* TOY_TOY_INCLUDE_TOY_CODE_H */
