/* Generated by gep (123/06/18 13:34:17) copyright (c) 2008 IRIT - UPS */

#ifndef GLISS_TOY_INCLUDE_TOY_DECODE_H
#define GLISS_TOY_INCLUDE_TOY_DECODE_H


#if defined(__cplusplus)
extern  "C"
{
#endif

#define TOY_DECODE_STATE
#define TOY_DECODE_INIT(s)
#define TOY_DECODE_DESTROY(s)

#if defined(__cplusplus)
}
#endif

#endif /* GLISS_TOY_INCLUDE_TOY_DECODE_H */
