/* Generated by gep (123/06/18 13:34:17) copyright (c) 2008 IRIT - UPS */

#ifndef GLISS_TOY_INCLUDE_TOY_FETCH_H
#define GLISS_TOY_INCLUDE_TOY_FETCH_H


#if defined(__cplusplus)
extern  "C"
{
#endif

#include "api.h"
#include "config.h"

#define TOY_FETCH_STATE
#define TOY_FETCH_INIT(s)
#define TOY_FETCH_DESTROY(s)

/* fetch structure */
struct toy_fetch_t
{
	/* the memory which we are supposed to fetch from, useful on Harvard architectures where we deal with several memories */
	toy_memory_t *mem;
};

#if defined(__cplusplus)
}
#endif

#endif /* GLISS_TOY_INCLUDE_TOY_FETCH_H */
