/* Generated by gep (123/06/18 13:34:17) copyright (c) 2008 IRIT - UPS */
#ifndef GLISS_TOY_INCLUDE_TOY_ID_H
#define GLISS_TOY_INCLUDE_TOY_ID_H

#define TOY_INSTRUCTIONS_NB 4

/* (toy_ident_t enumeration */
typedef enum toy_ident_t {
	TOY_UNKNOWN = 0,
	TOY_BEQ_S__S__D = 1,
	TOY_ADD_S__S__S = 2,
	TOY_SET_S___ID = 3,
	TOY_TOP
} toy_ident_t;

#endif /* GLISS_TOY_INCLUDE_TOY_ID_H */
