/* Generated by gep (123/06/18 13:34:17) copyright (c) 2008 IRIT - UPS */
#ifndef GLISS_TOY_INCLUDE_TOY_MACROS_H
#define GLISS_TOY_INCLUDE_TOY_MACROS_H

/* state access macros */
#define TOY_R ((state)->R)
#define TOY_PC ((state)->PC)

#define TOY_M ((state)->M)



/* instruction size macros, not used anymore, replaced by more efficient and less costly */
/*#define TOY_BEQ_S__S__D_SIZE	16
#define TOY_ADD_S__S__S_SIZE	16
#define TOY_SET_S___ID_SIZE	16
*/


/* parameter access and instruction size macros */
#define TOY_UNKNOWN___IADDR			((inst)->addr)
#define TOY_UNKNOWN___ISIZE			16
#define TOY_BEQ_S__S__D___IADDR		((inst)->addr)
#define TOY_BEQ_S__S__D___ISIZE		16
#define TOY_BEQ_S__S__D_x_r2_i		((inst)->instrinput[0].val.uint8)
#define TOY_BEQ_S__S__D_x_r1_i		((inst)->instrinput[1].val.uint8)
#define TOY_BEQ_S__S__D_x_off		((inst)->instrinput[2].val.int8)
#define TOY_ADD_S__S__S___IADDR		((inst)->addr)
#define TOY_ADD_S__S__S___ISIZE		16
#define TOY_ADD_S__S__S_x_s1_i		((inst)->instrinput[0].val.uint8)
#define TOY_ADD_S__S__S_x_d_i		((inst)->instrinput[1].val.uint8)
#define TOY_ADD_S__S__S_x_s2_i		((inst)->instrinput[2].val.uint8)
#define TOY_SET_S___ID___IADDR		((inst)->addr)
#define TOY_SET_S___ID___ISIZE		16
#define TOY_SET_S___ID_x_imm		((inst)->instrinput[0].val.int8)
#define TOY_SET_S___ID_x_r_i		((inst)->instrinput[1].val.uint8)


#endif /* GLISS_TOY_INCLUDE_TOY_MACROS_H */
